# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly

# matrix:
#   allow_failures:
#     - julia: nightly

dist: trusty

sudo: required

services:
  - docker

before_install:
  - echo "**** pulling Docker image"
  - docker pull tkpapp/texlive-julia-minimal
notifications:
  email: false
script:
  - echo "**** running Docker"
  - docker run --env-file travis_docker_env.list -t -a STDOUT -a STDIN -a STDERR -v $PWD:/mnt tkpapp/texlive-julia-minimal /mnt/travis_docker_test_script.sh $TRAVIS_JULIA_VERSION
after_success:
  # push coverage results to Coveralls, .cov files were copied back by script above
  - echo "**** submitting coverage information"
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
        using Coverage; Codecov.submit(Codecov.process_folder())'
